title: Florian BÃ¼rger
email: florian@florianbuerger.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Florian. I make apps while travelling the world.
baseurl: ""
url: "http://florianbuerger.com"
twitter_username: florianbuerger
github_username:  florianbuerger

markdown: kramdown
permalinks: pretty

navigation:
  - title: start here
    url: /
  - title: hire me
    url: /hire
  - title: blog
    url: /blog
  - title: my story
    url: /about
